apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-wf-dag-
spec:
  entrypoint: dag-template
  templates:
    - name: dag-template
      dag:
        tasks:
          - name: A
            template: container-template
          - name: B
            template: script-template
            dependencies: [A]
          - name: C  # Fixed from Cyrillic "паmе" to Latin "name"
            template: resource-template
            dependencies: [A]
          - name: D
            template: suspend-template
            dependencies: [B, C]

    - name: container-template
      container:
        image: alpine
        command: ["/bin/sh", "-c"]
        args: ["echo hello from container template"]

    - name: script-template
      script:
        image: python:alpine3.6
        command: ["python"]
        source: |
          import random
          i = random.randint(1, 10)
          print(i)

    - name: resource-template
      resource:
        action: create
        manifest: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            generateName: argo-wf-resource-template-cm-
          data:
            created_by: argo-workflows

    - name: suspend-template
      suspend:
        duration: "20s"

